# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: play.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='play.proto',
  package='',
  serialized_pb=_b('\n\nplay.proto\"5\n\nm_4001_tos\x12\x0f\n\x07operate\x18\x01 \x02(\r\x12\x16\n\x0eoperater_value\x18\x02 \x01(\x05\"\x1d\n\nm_4001_toc\x12\x0f\n\x07operate\x18\x01 \x02(\r\"1\n\nm_4002_toc\x12\x12\n\naccount_id\x18\x01 \x02(\r\x12\x0f\n\x07operate\x18\x02 \x02(\r\"7\n\nm_4003_toc\x12\x1a\n\x12\x65xecute_account_id\x18\x01 \x02(\r\x12\r\n\x05\x63\x61rds\x18\x02 \x03(\r\"G\n\nm_4004_toc\x12!\n\nclose_info\x18\x01 \x03(\x0b\x32\r.p_close_info\x12\x16\n\x0ewin_account_id\x18\x02 \x02(\r\"\x8b\x01\n\x0cp_close_info\x12\x12\n\naccount_id\x18\x01 \x02(\r\x12\x12\n\ncard_count\x18\x02 \x02(\r\x12.\n\x0e\x64ispatch_cards\x18\x03 \x03(\x0b\x32\x16.p_poker_dispatch_card\x12\x14\n\x0cpoint_change\x18\x04 \x02(\x05\x12\r\n\x05point\x18\x05 \x01(\x05\"(\n\x15p_poker_dispatch_card\x12\x0f\n\x07\x63\x61rd_id\x18\x01 \x03(\r\"\x0c\n\nm_4005_tos\"\x91\x01\n\nm_4006_toc\x12\x16\n\x0ewin_account_id\x18\x01 \x02(\r\x12\x13\n\x0bwin_card_id\x18\x02 \x02(\r\x12\x12\n\nwin_status\x18\x03 \x02(\r\x12\x17\n\x0flose_account_id\x18\x04 \x02(\r\x12)\n\nclose_info\x18\x05 \x03(\x0b\x32\x15.p_close_mahjong_info\"\x93\x01\n\x14p_close_mahjong_info\x12\x12\n\naccount_id\x18\x01 \x02(\r\x12)\n\naward_card\x18\x02 \x03(\x0b\x32\x15.p_mahjong_award_card\x12\x0f\n\x07\x63\x61rd_id\x18\x03 \x03(\r\x12\x14\n\x0cpoint_change\x18\x04 \x02(\x05\x12\x15\n\rcurrent_point\x18\x05 \x02(\x05\"\'\n\x14p_mahjong_award_card\x12\x0f\n\x07\x63\x61rd_id\x18\x01 \x03(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_M_4001_TOS = _descriptor.Descriptor(
  name='m_4001_tos',
  full_name='m_4001_tos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operate', full_name='m_4001_tos.operate', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operater_value', full_name='m_4001_tos.operater_value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=67,
)


_M_4001_TOC = _descriptor.Descriptor(
  name='m_4001_toc',
  full_name='m_4001_toc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operate', full_name='m_4001_toc.operate', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=98,
)


_M_4002_TOC = _descriptor.Descriptor(
  name='m_4002_toc',
  full_name='m_4002_toc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='m_4002_toc.account_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operate', full_name='m_4002_toc.operate', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=149,
)


_M_4003_TOC = _descriptor.Descriptor(
  name='m_4003_toc',
  full_name='m_4003_toc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='execute_account_id', full_name='m_4003_toc.execute_account_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cards', full_name='m_4003_toc.cards', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=206,
)


_M_4004_TOC = _descriptor.Descriptor(
  name='m_4004_toc',
  full_name='m_4004_toc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='close_info', full_name='m_4004_toc.close_info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='win_account_id', full_name='m_4004_toc.win_account_id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=279,
)


_P_CLOSE_INFO = _descriptor.Descriptor(
  name='p_close_info',
  full_name='p_close_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='p_close_info.account_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='card_count', full_name='p_close_info.card_count', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dispatch_cards', full_name='p_close_info.dispatch_cards', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point_change', full_name='p_close_info.point_change', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point', full_name='p_close_info.point', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=421,
)


_P_POKER_DISPATCH_CARD = _descriptor.Descriptor(
  name='p_poker_dispatch_card',
  full_name='p_poker_dispatch_card',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='card_id', full_name='p_poker_dispatch_card.card_id', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=463,
)


_M_4005_TOS = _descriptor.Descriptor(
  name='m_4005_tos',
  full_name='m_4005_tos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=465,
  serialized_end=477,
)


_M_4006_TOC = _descriptor.Descriptor(
  name='m_4006_toc',
  full_name='m_4006_toc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='win_account_id', full_name='m_4006_toc.win_account_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='win_card_id', full_name='m_4006_toc.win_card_id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='win_status', full_name='m_4006_toc.win_status', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lose_account_id', full_name='m_4006_toc.lose_account_id', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='close_info', full_name='m_4006_toc.close_info', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=480,
  serialized_end=625,
)


_P_CLOSE_MAHJONG_INFO = _descriptor.Descriptor(
  name='p_close_mahjong_info',
  full_name='p_close_mahjong_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='p_close_mahjong_info.account_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='award_card', full_name='p_close_mahjong_info.award_card', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='card_id', full_name='p_close_mahjong_info.card_id', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point_change', full_name='p_close_mahjong_info.point_change', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='current_point', full_name='p_close_mahjong_info.current_point', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=628,
  serialized_end=775,
)


_P_MAHJONG_AWARD_CARD = _descriptor.Descriptor(
  name='p_mahjong_award_card',
  full_name='p_mahjong_award_card',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='card_id', full_name='p_mahjong_award_card.card_id', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=777,
  serialized_end=816,
)

_M_4004_TOC.fields_by_name['close_info'].message_type = _P_CLOSE_INFO
_P_CLOSE_INFO.fields_by_name['dispatch_cards'].message_type = _P_POKER_DISPATCH_CARD
_M_4006_TOC.fields_by_name['close_info'].message_type = _P_CLOSE_MAHJONG_INFO
_P_CLOSE_MAHJONG_INFO.fields_by_name['award_card'].message_type = _P_MAHJONG_AWARD_CARD
DESCRIPTOR.message_types_by_name['m_4001_tos'] = _M_4001_TOS
DESCRIPTOR.message_types_by_name['m_4001_toc'] = _M_4001_TOC
DESCRIPTOR.message_types_by_name['m_4002_toc'] = _M_4002_TOC
DESCRIPTOR.message_types_by_name['m_4003_toc'] = _M_4003_TOC
DESCRIPTOR.message_types_by_name['m_4004_toc'] = _M_4004_TOC
DESCRIPTOR.message_types_by_name['p_close_info'] = _P_CLOSE_INFO
DESCRIPTOR.message_types_by_name['p_poker_dispatch_card'] = _P_POKER_DISPATCH_CARD
DESCRIPTOR.message_types_by_name['m_4005_tos'] = _M_4005_TOS
DESCRIPTOR.message_types_by_name['m_4006_toc'] = _M_4006_TOC
DESCRIPTOR.message_types_by_name['p_close_mahjong_info'] = _P_CLOSE_MAHJONG_INFO
DESCRIPTOR.message_types_by_name['p_mahjong_award_card'] = _P_MAHJONG_AWARD_CARD

m_4001_tos = _reflection.GeneratedProtocolMessageType('m_4001_tos', (_message.Message,), dict(
  DESCRIPTOR = _M_4001_TOS,
  __module__ = 'play_pb2'
  # @@protoc_insertion_point(class_scope:m_4001_tos)
  ))
_sym_db.RegisterMessage(m_4001_tos)

m_4001_toc = _reflection.GeneratedProtocolMessageType('m_4001_toc', (_message.Message,), dict(
  DESCRIPTOR = _M_4001_TOC,
  __module__ = 'play_pb2'
  # @@protoc_insertion_point(class_scope:m_4001_toc)
  ))
_sym_db.RegisterMessage(m_4001_toc)

m_4002_toc = _reflection.GeneratedProtocolMessageType('m_4002_toc', (_message.Message,), dict(
  DESCRIPTOR = _M_4002_TOC,
  __module__ = 'play_pb2'
  # @@protoc_insertion_point(class_scope:m_4002_toc)
  ))
_sym_db.RegisterMessage(m_4002_toc)

m_4003_toc = _reflection.GeneratedProtocolMessageType('m_4003_toc', (_message.Message,), dict(
  DESCRIPTOR = _M_4003_TOC,
  __module__ = 'play_pb2'
  # @@protoc_insertion_point(class_scope:m_4003_toc)
  ))
_sym_db.RegisterMessage(m_4003_toc)

m_4004_toc = _reflection.GeneratedProtocolMessageType('m_4004_toc', (_message.Message,), dict(
  DESCRIPTOR = _M_4004_TOC,
  __module__ = 'play_pb2'
  # @@protoc_insertion_point(class_scope:m_4004_toc)
  ))
_sym_db.RegisterMessage(m_4004_toc)

p_close_info = _reflection.GeneratedProtocolMessageType('p_close_info', (_message.Message,), dict(
  DESCRIPTOR = _P_CLOSE_INFO,
  __module__ = 'play_pb2'
  # @@protoc_insertion_point(class_scope:p_close_info)
  ))
_sym_db.RegisterMessage(p_close_info)

p_poker_dispatch_card = _reflection.GeneratedProtocolMessageType('p_poker_dispatch_card', (_message.Message,), dict(
  DESCRIPTOR = _P_POKER_DISPATCH_CARD,
  __module__ = 'play_pb2'
  # @@protoc_insertion_point(class_scope:p_poker_dispatch_card)
  ))
_sym_db.RegisterMessage(p_poker_dispatch_card)

m_4005_tos = _reflection.GeneratedProtocolMessageType('m_4005_tos', (_message.Message,), dict(
  DESCRIPTOR = _M_4005_TOS,
  __module__ = 'play_pb2'
  # @@protoc_insertion_point(class_scope:m_4005_tos)
  ))
_sym_db.RegisterMessage(m_4005_tos)

m_4006_toc = _reflection.GeneratedProtocolMessageType('m_4006_toc', (_message.Message,), dict(
  DESCRIPTOR = _M_4006_TOC,
  __module__ = 'play_pb2'
  # @@protoc_insertion_point(class_scope:m_4006_toc)
  ))
_sym_db.RegisterMessage(m_4006_toc)

p_close_mahjong_info = _reflection.GeneratedProtocolMessageType('p_close_mahjong_info', (_message.Message,), dict(
  DESCRIPTOR = _P_CLOSE_MAHJONG_INFO,
  __module__ = 'play_pb2'
  # @@protoc_insertion_point(class_scope:p_close_mahjong_info)
  ))
_sym_db.RegisterMessage(p_close_mahjong_info)

p_mahjong_award_card = _reflection.GeneratedProtocolMessageType('p_mahjong_award_card', (_message.Message,), dict(
  DESCRIPTOR = _P_MAHJONG_AWARD_CARD,
  __module__ = 'play_pb2'
  # @@protoc_insertion_point(class_scope:p_mahjong_award_card)
  ))
_sym_db.RegisterMessage(p_mahjong_award_card)


# @@protoc_insertion_point(module_scope)
