# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recharge.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='recharge.proto',
  package='',
  serialized_pb=_b('\n\x0erecharge.proto\"-\n\nm_9101_tos\x12\r\n\x05money\x18\x01 \x02(\r\x12\x10\n\x08proxy_id\x18\x02 \x02(\t\"\xa4\x01\n\nm_9101_toc\x12\r\n\x05money\x18\x01 \x02(\r\x12\x10\n\x08proxy_id\x18\x02 \x02(\t\x12\r\n\x05\x61ppid\x18\x03 \x02(\t\x12\x0e\n\x06mch_id\x18\x04 \x02(\t\x12\x11\n\tprepay_id\x18\x05 \x02(\t\x12\x10\n\x08_package\x18\x06 \x02(\t\x12\x10\n\x08noncestr\x18\x07 \x02(\t\x12\x11\n\ttimestamp\x18\x08 \x02(\t\x12\x0c\n\x04sign\x18\t \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_M_9101_TOS = _descriptor.Descriptor(
  name='m_9101_tos',
  full_name='m_9101_tos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='money', full_name='m_9101_tos.money', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='proxy_id', full_name='m_9101_tos.proxy_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=63,
)


_M_9101_TOC = _descriptor.Descriptor(
  name='m_9101_toc',
  full_name='m_9101_toc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='money', full_name='m_9101_toc.money', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='proxy_id', full_name='m_9101_toc.proxy_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='appid', full_name='m_9101_toc.appid', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mch_id', full_name='m_9101_toc.mch_id', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prepay_id', full_name='m_9101_toc.prepay_id', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='_package', full_name='m_9101_toc._package', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='noncestr', full_name='m_9101_toc.noncestr', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='m_9101_toc.timestamp', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sign', full_name='m_9101_toc.sign', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=230,
)

DESCRIPTOR.message_types_by_name['m_9101_tos'] = _M_9101_TOS
DESCRIPTOR.message_types_by_name['m_9101_toc'] = _M_9101_TOC

m_9101_tos = _reflection.GeneratedProtocolMessageType('m_9101_tos', (_message.Message,), dict(
  DESCRIPTOR = _M_9101_TOS,
  __module__ = 'recharge_pb2'
  # @@protoc_insertion_point(class_scope:m_9101_tos)
  ))
_sym_db.RegisterMessage(m_9101_tos)

m_9101_toc = _reflection.GeneratedProtocolMessageType('m_9101_toc', (_message.Message,), dict(
  DESCRIPTOR = _M_9101_TOC,
  __module__ = 'recharge_pb2'
  # @@protoc_insertion_point(class_scope:m_9101_toc)
  ))
_sym_db.RegisterMessage(m_9101_toc)


# @@protoc_insertion_point(module_scope)
