# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='system.proto',
  package='',
  serialized_pb=_b('\n\x0csystem.proto\"\x1d\n\nm_9001_toc\x12\x0f\n\x07\x63ontent\x18\x01 \x02(\t\"\x17\n\nm_9002_toc\x12\t\n\x01t\x18\x01 \x02(\r\"1\n\nm_9003_toc\x12#\n\x0brole_change\x18\x01 \x03(\x0b\x32\x0e.p_role_change\":\n\rp_role_change\x12\x13\n\x0b\x63hange_type\x18\x01 \x02(\r\x12\x14\n\x0c\x63hange_value\x18\x02 \x02(\r\"\x1d\n\nm_9004_toc\x12\x0f\n\x07\x63ontent\x18\x01 \x02(\t\"/\n\nm_9005_toc\x12!\n\x07\x63hanges\x18\x01 \x03(\x0b\x32\x10.p_change_string\"<\n\x0fp_change_string\x12\x13\n\x0b\x63hange_type\x18\x01 \x02(\r\x12\x14\n\x0c\x63hange_value\x18\x02 \x02(\t\"\x1d\n\nm_9006_tos\x12\x0f\n\x07room_id\x18\x01 \x01(\r\"\x0c\n\nm_9006_toc')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_M_9001_TOC = _descriptor.Descriptor(
  name='m_9001_toc',
  full_name='m_9001_toc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='m_9001_toc.content', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=45,
)


_M_9002_TOC = _descriptor.Descriptor(
  name='m_9002_toc',
  full_name='m_9002_toc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='t', full_name='m_9002_toc.t', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=70,
)


_M_9003_TOC = _descriptor.Descriptor(
  name='m_9003_toc',
  full_name='m_9003_toc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role_change', full_name='m_9003_toc.role_change', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=121,
)


_P_ROLE_CHANGE = _descriptor.Descriptor(
  name='p_role_change',
  full_name='p_role_change',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='change_type', full_name='p_role_change.change_type', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='change_value', full_name='p_role_change.change_value', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=181,
)


_M_9004_TOC = _descriptor.Descriptor(
  name='m_9004_toc',
  full_name='m_9004_toc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='m_9004_toc.content', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=212,
)


_M_9005_TOC = _descriptor.Descriptor(
  name='m_9005_toc',
  full_name='m_9005_toc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='changes', full_name='m_9005_toc.changes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=261,
)


_P_CHANGE_STRING = _descriptor.Descriptor(
  name='p_change_string',
  full_name='p_change_string',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='change_type', full_name='p_change_string.change_type', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='change_value', full_name='p_change_string.change_value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=323,
)


_M_9006_TOS = _descriptor.Descriptor(
  name='m_9006_tos',
  full_name='m_9006_tos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='room_id', full_name='m_9006_tos.room_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=354,
)


_M_9006_TOC = _descriptor.Descriptor(
  name='m_9006_toc',
  full_name='m_9006_toc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=368,
)

_M_9003_TOC.fields_by_name['role_change'].message_type = _P_ROLE_CHANGE
_M_9005_TOC.fields_by_name['changes'].message_type = _P_CHANGE_STRING
DESCRIPTOR.message_types_by_name['m_9001_toc'] = _M_9001_TOC
DESCRIPTOR.message_types_by_name['m_9002_toc'] = _M_9002_TOC
DESCRIPTOR.message_types_by_name['m_9003_toc'] = _M_9003_TOC
DESCRIPTOR.message_types_by_name['p_role_change'] = _P_ROLE_CHANGE
DESCRIPTOR.message_types_by_name['m_9004_toc'] = _M_9004_TOC
DESCRIPTOR.message_types_by_name['m_9005_toc'] = _M_9005_TOC
DESCRIPTOR.message_types_by_name['p_change_string'] = _P_CHANGE_STRING
DESCRIPTOR.message_types_by_name['m_9006_tos'] = _M_9006_TOS
DESCRIPTOR.message_types_by_name['m_9006_toc'] = _M_9006_TOC

m_9001_toc = _reflection.GeneratedProtocolMessageType('m_9001_toc', (_message.Message,), dict(
  DESCRIPTOR = _M_9001_TOC,
  __module__ = 'system_pb2'
  # @@protoc_insertion_point(class_scope:m_9001_toc)
  ))
_sym_db.RegisterMessage(m_9001_toc)

m_9002_toc = _reflection.GeneratedProtocolMessageType('m_9002_toc', (_message.Message,), dict(
  DESCRIPTOR = _M_9002_TOC,
  __module__ = 'system_pb2'
  # @@protoc_insertion_point(class_scope:m_9002_toc)
  ))
_sym_db.RegisterMessage(m_9002_toc)

m_9003_toc = _reflection.GeneratedProtocolMessageType('m_9003_toc', (_message.Message,), dict(
  DESCRIPTOR = _M_9003_TOC,
  __module__ = 'system_pb2'
  # @@protoc_insertion_point(class_scope:m_9003_toc)
  ))
_sym_db.RegisterMessage(m_9003_toc)

p_role_change = _reflection.GeneratedProtocolMessageType('p_role_change', (_message.Message,), dict(
  DESCRIPTOR = _P_ROLE_CHANGE,
  __module__ = 'system_pb2'
  # @@protoc_insertion_point(class_scope:p_role_change)
  ))
_sym_db.RegisterMessage(p_role_change)

m_9004_toc = _reflection.GeneratedProtocolMessageType('m_9004_toc', (_message.Message,), dict(
  DESCRIPTOR = _M_9004_TOC,
  __module__ = 'system_pb2'
  # @@protoc_insertion_point(class_scope:m_9004_toc)
  ))
_sym_db.RegisterMessage(m_9004_toc)

m_9005_toc = _reflection.GeneratedProtocolMessageType('m_9005_toc', (_message.Message,), dict(
  DESCRIPTOR = _M_9005_TOC,
  __module__ = 'system_pb2'
  # @@protoc_insertion_point(class_scope:m_9005_toc)
  ))
_sym_db.RegisterMessage(m_9005_toc)

p_change_string = _reflection.GeneratedProtocolMessageType('p_change_string', (_message.Message,), dict(
  DESCRIPTOR = _P_CHANGE_STRING,
  __module__ = 'system_pb2'
  # @@protoc_insertion_point(class_scope:p_change_string)
  ))
_sym_db.RegisterMessage(p_change_string)

m_9006_tos = _reflection.GeneratedProtocolMessageType('m_9006_tos', (_message.Message,), dict(
  DESCRIPTOR = _M_9006_TOS,
  __module__ = 'system_pb2'
  # @@protoc_insertion_point(class_scope:m_9006_tos)
  ))
_sym_db.RegisterMessage(m_9006_tos)

m_9006_toc = _reflection.GeneratedProtocolMessageType('m_9006_toc', (_message.Message,), dict(
  DESCRIPTOR = _M_9006_TOC,
  __module__ = 'system_pb2'
  # @@protoc_insertion_point(class_scope:m_9006_toc)
  ))
_sym_db.RegisterMessage(m_9006_toc)


# @@protoc_insertion_point(module_scope)
