GRANT USAGE ON * . * TO 'bbg'@'localhost' IDENTIFIED BY 'bbg' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 ;

DROP DATABASE IF EXISTS `bbg_server`;
CREATE DATABASE `bbg_server` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON `bbg_server` . * TO 'bbg'@'localhost' WITH GRANT OPTION;
